# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to Azure App Service

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
  

env:
  AZURE_WEBAPP_NAME: 'werewolf-api-dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    # Download Artifact
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        workflow: Build
        workflow_conclusion: success
        name: backend-app
        path: ./backend-app
    
    # Display file structures
    - name: Display structure of downloaded files
      run: ls -R
      
    # Deploy to Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './backend-app'

