# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to Azure App Service

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  AZURE_WEBAPP_NAME: 'werewolf-api-dev'
  AZURE_WEBAPP_PACKAGE_PATH: './src/'
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    # Checkout the repo
    - uses: actions/checkout@v3
    
    # Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
  
    # Run dotnet build and test
    - name: dontet restore, build and test
      working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      run: |
          dotnet restore 
          dotnet build -c Release --no-restore 
          dotnet test -c Release --no-build --verbosity normal
          
    # Run dotnet publish
    - name: Publish
      run: |
          dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -c Release -o publish  -r linux-x64 --self-contained true /p:UseAppHost=true
    
    - uses: actions/upload-artifact@v3
      with:
        name: ${{env.AZURE_WEBAPP_NAME}}
        path: publish
        
    # Deploy to Azure App Service
    #- name: Deploy to Azure App Service
    #  uses: azure/webapps-deploy@v2
    #  with:
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #    publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
    #    package: './publish'
